// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYHCe9MEZ37h8erHNd4C2bEK9CSlPYVo',
    appId: '1:11333191970:web:cc5ee0d1c97b84e15bbd7b',
    messagingSenderId: '11333191970',
    projectId: 'myapp-7f602',
    authDomain: 'myapp-7f602.firebaseapp.com',
    storageBucket: 'myapp-7f602.appspot.com',
    measurementId: 'G-X6YMWP7R6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRYd2vChl-FJ2NvjiPhqrUjLywr9ORws',
    appId: '1:11333191970:android:879dc04137b96f2d5bbd7b',
    messagingSenderId: '11333191970',
    projectId: 'myapp-7f602',
    storageBucket: 'myapp-7f602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONyvRpKQ-nC9Y4coQbzOkOnBKUd_XbM0',
    appId: '1:11333191970:ios:45980f6b31a583365bbd7b',
    messagingSenderId: '11333191970',
    projectId: 'myapp-7f602',
    storageBucket: 'myapp-7f602.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONyvRpKQ-nC9Y4coQbzOkOnBKUd_XbM0',
    appId: '1:11333191970:ios:45980f6b31a583365bbd7b',
    messagingSenderId: '11333191970',
    projectId: 'myapp-7f602',
    storageBucket: 'myapp-7f602.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkYHCe9MEZ37h8erHNd4C2bEK9CSlPYVo',
    appId: '1:11333191970:web:36ae7c08f9feb8ac5bbd7b',
    messagingSenderId: '11333191970',
    projectId: 'myapp-7f602',
    authDomain: 'myapp-7f602.firebaseapp.com',
    storageBucket: 'myapp-7f602.appspot.com',
    measurementId: 'G-08BNH7R53Q',
  );
}
